[workspace]
resolver = "2"

members = ["cli", "core"]

[workspace.package]
version = "0.7.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate's programmatic testing framework."
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/paritytech/try-runtime-cli"
repository = "https://github.com/paritytech/try-runtime-cli/"

[workspace.dependencies]
array-bytes = { version = "6.2.2" }
assert_cmd = { version = "2.0.10" }
async-trait = { version = "0.1.57" }
bytesize = { version = "1.2.0" }
clap = { version = "4.0.9" }
env_logger = { version = "0.10.0" }
hex = { version = "0.4.3", default-features = false }
itertools = { version = "0.11.0" }
log = { version = "0.4.17" }
parity-scale-codec = { version = "3.6.12" }
regex = { version = "1.7.3" }
serde = { version = "1.0.188" }
serde_json = { version = "1.0.85" }
strum = "0.25"
strum_macros = "0.25"
tempfile = { version = "3.1.0" }
tokio = { version = "1.37.0" }
zstd = { version = "0.11.2", default-features = false }

# Polkadot SDK
frame-remote-externalities = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }
frame-try-runtime = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }
frame-support = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }
frame-system = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }

sc-cli = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }
sc-executor = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }
sc-service = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }

sp-api = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }
sp-consensus-aura = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }
sp-consensus-babe = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }
sp-externalities = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }
sp-inherents = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }
sp-io = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }
sp-keystore = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }
sp-rpc = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }
sp-state-machine = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }
sp-storage = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }
sp-std = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }
sp-timestamp = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }
sp-transaction-storage-proof = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }
sp-version = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }
sp-weights = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }

substrate-cli-test-utils = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }
substrate-rpc-client = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }

polkadot-primitives = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }
cumulus-primitives-parachain-inherent = { git = "https://github.com/paritytech/polkadot-sdk", rev = "caa19463b8bd5e4ca4635ab872597251e5e6b1a5" }
cumulus-primitives-core = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }
cumulus-client-parachain-inherent = { git = "https://github.com/paritytech/polkadot-sdk", rev = "602352c458678ea6cd08fbe3bde9b053b301824c" }

# Local
try-runtime-core = { path = "core" }
