name: Build and Attach Binaries to Release

on:
  release:
    types:
      - created

jobs:
  build_and_upload:
    strategy:
      matrix:
        platform: 
          - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu.2.17 }
          - { os: macos-latest, target: x86_64-apple-darwin }

    runs-on: ${{ matrix.platform.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: "3.6.1"

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Build Rust project (linux)
      if: matrix.platform.os == 'ubuntu-latest'
      run: |
        sudo apt install --assume-yes build-essential git clang curl libssl-dev protobuf-compiler
        pip3 install ziglang
        cargo install cargo-zigbuild
        cargo zigbuild --release --target ${{ matrix.platform.target }}

    - name: Build Rust project (macos)
      if: matrix.platform.os == 'macos-latest'
      run: cargo build --release --target ${{ matrix.platform.target }}

    - name: Upload Binary to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./target/${{ matrix.platform.target }}/release/try-runtime
        asset_name: try-runtime-${{ matrix.platform.target }}
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
